[2023-12-12T01:15:01.927+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_rtgs_data_processing_airflow_dag.airbyte_check_sync_journal_entries scheduled__2023-12-11T00:00:00+00:00 [queued]>
[2023-12-12T01:15:01.943+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_rtgs_data_processing_airflow_dag.airbyte_check_sync_journal_entries scheduled__2023-12-11T00:00:00+00:00 [queued]>
[2023-12-12T01:15:01.948+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-12T01:15:02.037+0000] {taskinstance.py:1382} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync_journal_entries> on 2023-12-11 00:00:00+00:00
[2023-12-12T01:15:02.053+0000] {standard_task_runner.py:57} INFO - Started process 118 to run task
[2023-12-12T01:15:02.081+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airbyte_rtgs_data_processing_***_dag', 'airbyte_check_sync_journal_entries', 'scheduled__2023-12-11T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/rtgs_data_processing.py', '--cfg-path', '/tmp/tmplip3xng3']
[2023-12-12T01:15:02.094+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask airbyte_check_sync_journal_entries
[2023-12-12T01:15:02.194+0000] {task_command.py:416} INFO - Running <TaskInstance: airbyte_rtgs_data_processing_airflow_dag.airbyte_check_sync_journal_entries scheduled__2023-12-11T00:00:00+00:00 [running]> on host 86ddea81acd7
[2023-12-12T01:15:02.974+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbyte_rtgs_data_processing_***_dag' AIRFLOW_CTX_TASK_ID='airbyte_check_sync_journal_entries' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-11T00:00:00+00:00'
[2023-12-12T01:15:02.997+0000] {base.py:73} INFO - Using connection ID '***-call-to-airbyte' for task execution.
[2023-12-12T01:15:03.031+0000] {airbyte.py:80} INFO - Waiting for job 17 to complete.
[2023-12-12T01:16:03.142+0000] {base.py:73} INFO - Using connection ID '***-call-to-airbyte' for task execution.
[2023-12-12T01:16:03.334+0000] {airbyte.py:80} INFO - Waiting for job 17 to complete.
[2023-12-12T01:17:03.373+0000] {base.py:73} INFO - Using connection ID '***-call-to-airbyte' for task execution.
[2023-12-12T01:17:03.399+0000] {airbyte.py:80} INFO - Waiting for job 17 to complete.
[2023-12-12T01:18:03.435+0000] {base.py:73} INFO - Using connection ID '***-call-to-airbyte' for task execution.
[2023-12-12T01:18:03.482+0000] {airbyte.py:80} INFO - Waiting for job 17 to complete.
[2023-12-12T01:19:03.519+0000] {base.py:73} INFO - Using connection ID '***-call-to-airbyte' for task execution.
[2023-12-12T01:19:03.627+0000] {airbyte.py:80} INFO - Waiting for job 17 to complete.
[2023-12-12T01:20:03.662+0000] {base.py:73} INFO - Using connection ID '***-call-to-airbyte' for task execution.
[2023-12-12T01:20:03.758+0000] {airbyte.py:80} INFO - Waiting for job 17 to complete.
[2023-12-12T01:21:03.780+0000] {base.py:73} INFO - Using connection ID '***-call-to-airbyte' for task execution.
[2023-12-12T01:21:03.837+0000] {airbyte.py:80} INFO - Waiting for job 17 to complete.
[2023-12-12T01:22:03.855+0000] {base.py:73} INFO - Using connection ID '***-call-to-airbyte' for task execution.
[2023-12-12T01:22:03.929+0000] {airbyte.py:80} INFO - Waiting for job 17 to complete.
[2023-12-12T01:23:03.954+0000] {base.py:73} INFO - Using connection ID '***-call-to-airbyte' for task execution.
[2023-12-12T01:23:04.036+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 67, in poke
    raise AirflowException(message)
airflow.exceptions.AirflowException: Job failed: 
<Response [200]>
[2023-12-12T01:23:04.042+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=airbyte_rtgs_data_processing_***_dag, task_id=airbyte_check_sync_journal_entries, execution_date=20231211T000000, start_date=20231212T011501, end_date=20231212T012304
[2023-12-12T01:23:04.057+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 64 for task airbyte_check_sync_journal_entries (Job failed: 
<Response [200]>; 118)
[2023-12-12T01:23:04.090+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T01:23:04.494+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
