[2023-12-11T16:38:11.154+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_mambu_data_processing_airflow_dag.airbyte_trigger_sync_deposit_transactions manual__2023-12-11T16:38:05.211495+00:00 [queued]>
[2023-12-11T16:38:11.162+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_mambu_data_processing_airflow_dag.airbyte_trigger_sync_deposit_transactions manual__2023-12-11T16:38:05.211495+00:00 [queued]>
[2023-12-11T16:38:11.162+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-11T16:38:11.170+0000] {taskinstance.py:1382} INFO - Executing <Task(AirbyteTriggerSyncOperator): airbyte_trigger_sync_deposit_transactions> on 2023-12-11 16:38:05.211495+00:00
[2023-12-11T16:38:11.175+0000] {standard_task_runner.py:57} INFO - Started process 419 to run task
[2023-12-11T16:38:11.178+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airbyte_mambu_data_processing_***_dag', 'airbyte_trigger_sync_deposit_transactions', 'manual__2023-12-11T16:38:05.211495+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/mambu_data_processing.py', '--cfg-path', '/tmp/tmpdjmpmrib']
[2023-12-11T16:38:11.180+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask airbyte_trigger_sync_deposit_transactions
[2023-12-11T16:38:11.206+0000] {task_command.py:416} INFO - Running <TaskInstance: airbyte_mambu_data_processing_airflow_dag.airbyte_trigger_sync_deposit_transactions manual__2023-12-11T16:38:05.211495+00:00 [running]> on host 7a42d9ce34c3
[2023-12-11T16:38:11.627+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbyte_mambu_data_processing_***_dag' AIRFLOW_CTX_TASK_ID='airbyte_trigger_sync_deposit_transactions' AIRFLOW_CTX_EXECUTION_DATE='2023-12-11T16:38:05.211495+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-11T16:38:05.211495+00:00'
[2023-12-11T16:38:11.638+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 73, in execute
    job_object = self.hook.submit_sync_connection(connection_id=self.connection_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 92, in submit_sync_connection
    return self.run(
           ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/http/hooks/http.py", line 145, in run
    session = self.get_conn(headers)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/http/hooks/http.py", line 98, in get_conn
    conn = self.get_connection(self.http_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***-call-to-airbyte-deposit-transactions` isn't defined
[2023-12-11T16:38:11.645+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=airbyte_mambu_data_processing_***_dag, task_id=airbyte_trigger_sync_deposit_transactions, execution_date=20231211T163805, start_date=20231211T163811, end_date=20231211T163811
[2023-12-11T16:38:11.666+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task airbyte_trigger_sync_deposit_transactions (The conn_id `***-call-to-airbyte-deposit-transactions` isn't defined; 419)
[2023-12-11T16:38:11.690+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-11T16:38:11.729+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
