[2023-12-12T02:09:39.505+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_rtgs_data_processing_airflow_dag.rtgs_data_transformation.rtgs_journal_entries_clean.run manual__2023-12-12T02:07:10.325039+00:00 [queued]>
[2023-12-12T02:09:39.509+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_rtgs_data_processing_airflow_dag.rtgs_data_transformation.rtgs_journal_entries_clean.run manual__2023-12-12T02:07:10.325039+00:00 [queued]>
[2023-12-12T02:09:39.509+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-12T02:09:39.514+0000] {taskinstance.py:1382} INFO - Executing <Task(DbtRunLocalOperator): rtgs_data_transformation.rtgs_journal_entries_clean.run> on 2023-12-12 02:07:10.325039+00:00
[2023-12-12T02:09:39.518+0000] {standard_task_runner.py:57} INFO - Started process 404 to run task
[2023-12-12T02:09:39.520+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airbyte_rtgs_data_processing_***_dag', 'rtgs_data_transformation.rtgs_journal_entries_clean.run', 'manual__2023-12-12T02:07:10.325039+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/rtgs_data_processing.py', '--cfg-path', '/tmp/tmp560pau12']
[2023-12-12T02:09:39.522+0000] {standard_task_runner.py:85} INFO - Job 104: Subtask rtgs_data_transformation.rtgs_journal_entries_clean.run
[2023-12-12T02:09:39.547+0000] {task_command.py:416} INFO - Running <TaskInstance: airbyte_rtgs_data_processing_airflow_dag.rtgs_data_transformation.rtgs_journal_entries_clean.run manual__2023-12-12T02:07:10.325039+00:00 [running]> on host 86ddea81acd7
[2023-12-12T02:09:39.716+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbyte_rtgs_data_processing_***_dag' AIRFLOW_CTX_TASK_ID='rtgs_data_transformation.rtgs_journal_entries_clean.run' AIRFLOW_CTX_EXECUTION_DATE='2023-12-12T02:07:10.325039+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-12T02:07:10.325039+00:00'
[2023-12-12T02:09:39.717+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:39.716+0000[0m] {[34mlocal.py:[0m194} INFO[0m - [35m(astronomer-cosmos)[0m - Cloning project to writable temp directory /tmp/tmp0havr_gd from /opt/***/dags/dbt/rtgs[0m
[2023-12-12T02:09:39.716+0000] {local.py:194} INFO - Cloning project to writable temp directory /tmp/tmp0havr_gd from /opt/airflow/dags/dbt/rtgs
[2023-12-12T02:09:39.717+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:39.717+0000[0m] {[34mconfig.py:[0m220} INFO[0m - [35m(astronomer-cosmos)[0m - Using user-supplied profiles.yml at /opt/***/dags/dbt/rtgs/profiles.yml[0m
[2023-12-12T02:09:39.717+0000] {config.py:220} INFO - Using user-supplied profiles.yml at /opt/airflow/dags/dbt/rtgs/profiles.yml
[2023-12-12T02:09:39.718+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:39.718+0000[0m] {[34mlocal.py:[0m227} INFO[0m - [35m(astronomer-cosmos)[0m - Trying to run the command:
 ['/home/***/.local/bin/dbt', 'run', '--models', 'rtgs_journal_entries_clean', '--profiles-dir', '/opt/***/dags/dbt/rtgs', '--profile', 'staging', '--target', 'dev']
From /tmp/tmp0havr_gd[0m
[2023-12-12T02:09:39.718+0000] {local.py:227} INFO - Trying to run the command:
 ['/home/***/.local/bin/dbt', 'run', '--models', 'rtgs_journal_entries_clean', '--profiles-dir', '/opt/***/dags/dbt/rtgs', '--profile', 'staging', '--target', 'dev']
From /tmp/tmp0havr_gd
[2023-12-12T02:09:39.718+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:39.718+0000[0m] {[34mlocal.py:[0m228} INFO[0m - [35m(astronomer-cosmos)[0m - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])[0m
[2023-12-12T02:09:39.718+0000] {local.py:228} INFO - Using environment variables keys: dict_keys(['AIRFLOW_CTX_DAG_OWNER', 'AIRFLOW_CTX_DAG_ID', 'AIRFLOW_CTX_TASK_ID', 'AIRFLOW_CTX_EXECUTION_DATE', 'AIRFLOW_CTX_TRY_NUMBER', 'AIRFLOW_CTX_DAG_RUN_ID'])
[2023-12-12T02:09:39.718+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:39.718+0000[0m] {[34msubprocess.py:[0m60} INFO[0m - [35m(astronomer-cosmos)[0m - Tmp dir root location: 
 /tmp[0m
[2023-12-12T02:09:39.718+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2023-12-12T02:09:39.719+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:39.719+0000[0m] {[34msubprocess.py:[0m73} INFO[0m - [35m(astronomer-cosmos)[0m - Running command: ['/home/***/.local/bin/dbt', 'run', '--models', 'rtgs_journal_entries_clean', '--profiles-dir', '/opt/***/dags/dbt/rtgs', '--profile', 'staging', '--target', 'dev'][0m
[2023-12-12T02:09:39.719+0000] {subprocess.py:73} INFO - Running command: ['/home/***/.local/bin/dbt', 'run', '--models', 'rtgs_journal_entries_clean', '--profiles-dir', '/opt/***/dags/dbt/rtgs', '--profile', 'staging', '--target', 'dev']
[2023-12-12T02:09:39.724+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:39.724+0000[0m] {[34msubprocess.py:[0m84} INFO[0m - [35m(astronomer-cosmos)[0m - Command output:[0m
[2023-12-12T02:09:39.724+0000] {subprocess.py:84} INFO - Command output:
[2023-12-12T02:09:40.792+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:40.792+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:40  Running with dbt=1.5.9[0m
[2023-12-12T02:09:40.792+0000] {subprocess.py:94} INFO - [0m02:09:40  Running with dbt=1.5.9
[2023-12-12T02:09:40.860+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:40.860+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:40  Registered adapter: mysql=1.5.0-a1[0m
[2023-12-12T02:09:40.860+0000] {subprocess.py:94} INFO - [0m02:09:40  Registered adapter: mysql=1.5.0-a1
[2023-12-12T02:09:40.865+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:40.865+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:40  Unable to do partial parsing because saved manifest not found. Starting full parse.[0m
[2023-12-12T02:09:40.865+0000] {subprocess.py:94} INFO - [0m02:09:40  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2023-12-12T02:09:41.136+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.136+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.[0m
[2023-12-12T02:09:41.136+0000] {subprocess.py:94} INFO - [0m02:09:41  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-12-12T02:09:41.137+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.137+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - There are 1 unused configuration paths:[0m
[2023-12-12T02:09:41.137+0000] {subprocess.py:94} INFO - There are 1 unused configuration paths:
[2023-12-12T02:09:41.137+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.137+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - - models.journal_entries[0m
[2023-12-12T02:09:41.137+0000] {subprocess.py:94} INFO - - models.journal_entries
[2023-12-12T02:09:41.142+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.142+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 300 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups[0m
[2023-12-12T02:09:41.142+0000] {subprocess.py:94} INFO - [0m02:09:41  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 300 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-12-12T02:09:41.143+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.143+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41[0m
[2023-12-12T02:09:41.143+0000] {subprocess.py:94} INFO - [0m02:09:41
[2023-12-12T02:09:41.241+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.241+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41  Concurrency: 1 threads (target='dev')[0m
[2023-12-12T02:09:41.241+0000] {subprocess.py:94} INFO - [0m02:09:41  Concurrency: 1 threads (target='dev')
[2023-12-12T02:09:41.242+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.242+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41[0m
[2023-12-12T02:09:41.242+0000] {subprocess.py:94} INFO - [0m02:09:41
[2023-12-12T02:09:41.252+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.252+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41  1 of 1 START sql table model staging.rtgs_journal_entries_clean ................ [RUN][0m
[2023-12-12T02:09:41.252+0000] {subprocess.py:94} INFO - [0m02:09:41  1 of 1 START sql table model staging.rtgs_journal_entries_clean ................ [RUN]
[2023-12-12T02:09:41.297+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.297+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41  1 of 1 ERROR creating sql table model staging.rtgs_journal_entries_clean ....... [[31mERROR[0m in 0.04s][0m
[2023-12-12T02:09:41.297+0000] {subprocess.py:94} INFO - [0m02:09:41  1 of 1 ERROR creating sql table model staging.rtgs_journal_entries_clean ....... [[31mERROR[0m in 0.04s]
[2023-12-12T02:09:41.304+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.304+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41[0m
[2023-12-12T02:09:41.304+0000] {subprocess.py:94} INFO - [0m02:09:41
[2023-12-12T02:09:41.304+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.304+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41  Finished running 1 table model in 0 hours 0 minutes and 0.16 seconds (0.16s).[0m
[2023-12-12T02:09:41.304+0000] {subprocess.py:94} INFO - [0m02:09:41  Finished running 1 table model in 0 hours 0 minutes and 0.16 seconds (0.16s).
[2023-12-12T02:09:41.308+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.308+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41[0m
[2023-12-12T02:09:41.308+0000] {subprocess.py:94} INFO - [0m02:09:41
[2023-12-12T02:09:41.308+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.308+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41  [31mCompleted with 1 error and 0 warnings:[0m[0m
[2023-12-12T02:09:41.308+0000] {subprocess.py:94} INFO - [0m02:09:41  [31mCompleted with 1 error and 0 warnings:[0m
[2023-12-12T02:09:41.309+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.309+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41[0m
[2023-12-12T02:09:41.309+0000] {subprocess.py:94} INFO - [0m02:09:41
[2023-12-12T02:09:41.309+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.309+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41  [33mDatabase Error in model rtgs_journal_entries_clean (models/rtgs_journal_entries/rtgs_journal_entries_clean.sql)[0m[0m
[2023-12-12T02:09:41.309+0000] {subprocess.py:94} INFO - [0m02:09:41  [33mDatabase Error in model rtgs_journal_entries_clean (models/rtgs_journal_entries/rtgs_journal_entries_clean.sql)[0m
[2023-12-12T02:09:41.309+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.309+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41    1054 (42S22): Unknown column 'jeg._airbyte_journal_entries_hashid' in 'on clause'[0m
[2023-12-12T02:09:41.309+0000] {subprocess.py:94} INFO - [0m02:09:41    1054 (42S22): Unknown column 'jeg._airbyte_journal_entries_hashid' in 'on clause'
[2023-12-12T02:09:41.309+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.309+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41    compiled Code at target/run/rtgs/models/rtgs_journal_entries/rtgs_journal_entries_clean.sql[0m
[2023-12-12T02:09:41.309+0000] {subprocess.py:94} INFO - [0m02:09:41    compiled Code at target/run/rtgs/models/rtgs_journal_entries/rtgs_journal_entries_clean.sql
[2023-12-12T02:09:41.310+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.310+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41[0m
[2023-12-12T02:09:41.310+0000] {subprocess.py:94} INFO - [0m02:09:41
[2023-12-12T02:09:41.310+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:41.310+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [0m02:09:41  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1[0m
[2023-12-12T02:09:41.310+0000] {subprocess.py:94} INFO - [0m02:09:41  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2023-12-12T02:09:42.219+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:42.218+0000[0m] {[34msubprocess.py:[0m98} INFO[0m - [35m(astronomer-cosmos)[0m - Command exited with return code 1[0m
[2023-12-12T02:09:42.218+0000] {subprocess.py:98} INFO - Command exited with return code 1
[2023-12-12T02:09:42.233+0000] {local.py:110} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v9.json is above dbt-ol supported version 7. This might cause errors.
[2023-12-12T02:09:42.236+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:42.236+0000[0m] {[34mlocal.py:[0m244} INFO[0m - [35m(astronomer-cosmos)[0m - Inlets: [][0m
[2023-12-12T02:09:42.236+0000] {local.py:244} INFO - Inlets: []
[2023-12-12T02:09:42.236+0000] {log.py:232} WARNING - [[34m2023-12-12T02:09:42.236+0000[0m] {[34mlocal.py:[0m245} INFO[0m - [35m(astronomer-cosmos)[0m - Outlets: [][0m
[2023-12-12T02:09:42.236+0000] {local.py:245} INFO - Outlets: []
[2023-12-12T02:09:42.237+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-12T02:09:42.261+0000] {dag.py:3722} INFO - Setting next_dagrun for airbyte_rtgs_data_processing_***_dag to 2023-12-12T00:00:00+00:00, run_after=2023-12-13T00:00:00+00:00
[2023-12-12T02:09:42.277+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/cosmos/operators/local.py", line 452, in execute
    self.build_and_run_cmd(context=context, cmd_flags=cmd_flags)
  File "/home/airflow/.local/lib/python3.11/site-packages/cosmos/operators/local.py", line 362, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/cosmos/operators/local.py", line 249, in run_command
    self.exception_handling(result)
  File "/home/airflow/.local/lib/python3.11/site-packages/cosmos/operators/local.py", line 128, in exception_handling
    raise AirflowException(
airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m02:09:40  Running with dbt=1.5.9', '\x1b[0m02:09:40  Registered adapter: mysql=1.5.0-a1', '\x1b[0m02:09:40  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m02:09:41  [\x1b[33mWARNING\x1b[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.', 'There are 1 unused configuration paths:', '- models.journal_entries', '\x1b[0m02:09:41  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 300 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups', '\x1b[0m02:09:41', "\x1b[0m02:09:41  Concurrency: 1 threads (target='dev')", '\x1b[0m02:09:41', '\x1b[0m02:09:41  1 of 1 START sql table model staging.rtgs_journal_entries_clean ................ [RUN]', '\x1b[0m02:09:41  1 of 1 ERROR creating sql table model staging.rtgs_journal_entries_clean ....... [\x1b[31mERROR\x1b[0m in 0.04s]', '\x1b[0m02:09:41', '\x1b[0m02:09:41  Finished running 1 table model in 0 hours 0 minutes and 0.16 seconds (0.16s).', '\x1b[0m02:09:41', '\x1b[0m02:09:41  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m02:09:41', '\x1b[0m02:09:41  \x1b[33mDatabase Error in model rtgs_journal_entries_clean (models/rtgs_journal_entries/rtgs_journal_entries_clean.sql)\x1b[0m', "\x1b[0m02:09:41    1054 (42S22): Unknown column 'jeg._airbyte_journal_entries_hashid' in 'on clause'", '\x1b[0m02:09:41    compiled Code at target/run/rtgs/models/rtgs_journal_entries/rtgs_journal_entries_clean.sql', '\x1b[0m02:09:41', '\x1b[0m02:09:41  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1')
[2023-12-12T02:09:42.279+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=airbyte_rtgs_data_processing_***_dag, task_id=rtgs_data_transformation.rtgs_journal_entries_clean.run, execution_date=20231212T020710, start_date=20231212T020939, end_date=20231212T020942
[2023-12-12T02:09:42.284+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 104 for task rtgs_data_transformation.rtgs_journal_entries_clean.run (('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m02:09:40  Running with dbt=1.5.9', '\x1b[0m02:09:40  Registered adapter: mysql=1.5.0-a1', '\x1b[0m02:09:40  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m02:09:41  [\x1b[33mWARNING\x1b[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.', 'There are 1 unused configuration paths:', '- models.journal_entries', '\x1b[0m02:09:41  Found 1 model, 2 tests, 0 snapshots, 0 analyses, 300 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups', '\x1b[0m02:09:41', "\x1b[0m02:09:41  Concurrency: 1 threads (target='dev')", '\x1b[0m02:09:41', '\x1b[0m02:09:41  1 of 1 START sql table model staging.rtgs_journal_entries_clean ................ [RUN]', '\x1b[0m02:09:41  1 of 1 ERROR creating sql table model staging.rtgs_journal_entries_clean ....... [\x1b[31mERROR\x1b[0m in 0.04s]', '\x1b[0m02:09:41', '\x1b[0m02:09:41  Finished running 1 table model in 0 hours 0 minutes and 0.16 seconds (0.16s).', '\x1b[0m02:09:41', '\x1b[0m02:09:41  \x1b[31mCompleted with 1 error and 0 warnings:\x1b[0m', '\x1b[0m02:09:41', '\x1b[0m02:09:41  \x1b[33mDatabase Error in model rtgs_journal_entries_clean (models/rtgs_journal_entries/rtgs_journal_entries_clean.sql)\x1b[0m', "\x1b[0m02:09:41    1054 (42S22): Unknown column 'jeg._airbyte_journal_entries_hashid' in 'on clause'", '\x1b[0m02:09:41    compiled Code at target/run/rtgs/models/rtgs_journal_entries/rtgs_journal_entries_clean.sql', '\x1b[0m02:09:41', '\x1b[0m02:09:41  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1'); 404)
[2023-12-12T02:09:42.299+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T02:09:42.330+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
