[2023-12-12T01:26:09.140+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_rtgs_data_processing_airflow_dag.airbyte_check_sync_journal_entries manual__2023-12-12T01:25:44.782450+00:00 [queued]>
[2023-12-12T01:26:09.185+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_rtgs_data_processing_airflow_dag.airbyte_check_sync_journal_entries manual__2023-12-12T01:25:44.782450+00:00 [queued]>
[2023-12-12T01:26:09.186+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-12T01:26:09.240+0000] {taskinstance.py:1382} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync_journal_entries> on 2023-12-12 01:25:44.782450+00:00
[2023-12-12T01:26:09.252+0000] {standard_task_runner.py:57} INFO - Started process 320 to run task
[2023-12-12T01:26:09.257+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'airbyte_rtgs_data_processing_***_dag', 'airbyte_check_sync_journal_entries', 'manual__2023-12-12T01:25:44.782450+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/rtgs_data_processing.py', '--cfg-path', '/tmp/tmpik5dlqmp']
[2023-12-12T01:26:09.268+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask airbyte_check_sync_journal_entries
[2023-12-12T01:26:09.346+0000] {task_command.py:416} INFO - Running <TaskInstance: airbyte_rtgs_data_processing_airflow_dag.airbyte_check_sync_journal_entries manual__2023-12-12T01:25:44.782450+00:00 [running]> on host 86ddea81acd7
[2023-12-12T01:26:11.737+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='airbyte_rtgs_data_processing_***_dag' AIRFLOW_CTX_TASK_ID='airbyte_check_sync_journal_entries' AIRFLOW_CTX_EXECUTION_DATE='2023-12-12T01:25:44.782450+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-12T01:25:44.782450+00:00'
[2023-12-12T01:26:11.743+0000] {base.py:73} INFO - Using connection ID '***-call-to-airbyte' for task execution.
[2023-12-12T01:26:11.790+0000] {airbyte.py:80} INFO - Waiting for job 20 to complete.
[2023-12-12T01:27:11.805+0000] {base.py:73} INFO - Using connection ID '***-call-to-airbyte' for task execution.
[2023-12-12T01:27:11.848+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/airbyte/sensors/airbyte.py", line 73, in poke
    raise AirflowException(message)
airflow.exceptions.AirflowException: Job was cancelled: 
<Response [200]>
[2023-12-12T01:27:11.855+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=airbyte_rtgs_data_processing_***_dag, task_id=airbyte_check_sync_journal_entries, execution_date=20231212T012544, start_date=20231212T012609, end_date=20231212T012711
[2023-12-12T01:27:11.869+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 68 for task airbyte_check_sync_journal_entries (Job was cancelled: 
<Response [200]>; 320)
[2023-12-12T01:27:11.912+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-12T01:27:12.317+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
